[theme]
primaryColor = "#4F8BF9"  # Primary color (blue)
backgroundColor = "#FFFFFF"  # Background color (white)
secondaryBackgroundColor = "#F0F2F6"  # Secondary background (light gray)
textColor = "#000000"  # Text color (black)
font = "sans serif"